name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Validate with Maven
      run: mvn -B validate 

    - name: Compile with Maven
      run: mvn -B compile

    - name: Test with Maven
      run: mvn -B test

    - name: Package with Maven
      run: mvn -B package

    - name: Deploy to Nexus
      run: mvn -B deploy --settings .github/maven-settings.xml -X
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}


